organization: mimi
project_name: &project_name infra-core
namespace: mimi
env: development
tags:
  terraform: true
  team: devops
modules:
  vpc:
    name: infra-core-development
    subnets:
      - subnet-12345678901
      - subnet-01234567891
      - subnet-90123456781
