services:
  web:
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: ./Dockerfile.web
    depends_on:
      - api
      - db
    environment:
      - PORT=3000
      - API_HOST=http://api:3000
  api:
    ports:
      - 3001:3000
    build:
      context: .
      dockerfile: ./Dockerfile.api
    depends_on:
      - db
    environment:
      - PORT=3000
      - DB=database
      - DBUSER=admin
      - DBPASS=testpassw0rd
      - DBHOST=db
      - DBPORT=5432
  db:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_PASSWORD=testpassw0rd
      - POSTGRES_USER=admin
      - POSTGRES_DB=database
