name: Apply Infra

on:
  # Compare the preceeding commit of main -> to the current commit of the main branch.
  # (Note: To compare changes between the last pushed commit to the remote main branch set `since_last_remote_commit: true`)
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: apply infra
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: infra-live folder changed
        id: infra-changed
        uses: tj-actions/changed-files@v34
        with:
          files: |
            iac/infra-live/**
      - name: 'Terraform Init'
        if: steps.infra-changed.outputs.any_changed == 'true'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.8.0
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: './iac/infra-live'
          tf_actions_comment: true
        env:
          TF_WORKSPACE: dev
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
