name: Apply Infra

on:
  # Compare the preceeding commit of main -> to the current commit of the main branch.
  # (Note: To compare changes between the last pushed commit to the remote main branch set `since_last_remote_commit: true`)
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: apply infra
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: infra-live folder changed
        id: infra-changed
        uses: tj-actions/changed-files@v34
        with:
          files: |
            iac/infra-live/**
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.5
      - run: terraform init
        env:
          TF_WORKSPACE: development
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - id: plan
        run: terraform plan -no-color
        env:
          TF_WORKSPACE: development
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - run: echo ${{ steps.plan.outputs.stdout }}
      - run: echo ${{ steps.plan.outputs.stderr }}
      - run: echo ${{ steps.plan.outputs.exitcode }}
