name: Apply Infra

on:
  # Compare the preceeding commit of main -> to the current commit of the main branch.
  # (Note: To compare changes between the last pushed commit to the remote main branch set `since_last_remote_commit: true`)
  push:
    branches:
      - main

jobs:
  validate_and_plan:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: plan infra
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: infra-live folder changed
        id: infra-changed
        uses: tj-actions/changed-files@v34
        with:
          files: |
            iac/infra-live/**
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.5

      - name: Terraform fmt
        if: steps.infra-changed.outputs.any_changed == 'true'
        id: fmt
        run: terraform fmt -check
        continue-on-error: false
        working-directory: ./iac/infra-live

      - name: Terraform Init
        if: steps.infra-changed.outputs.any_changed == 'true'
        id: init
        run: terraform init
        working-directory: ./iac/infra-live
        env:
          TF_WORKSPACE: development
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Validate
        if: steps.infra-changed.outputs.any_changed == 'true'
        id: validate
        run: terraform validate -no-color
        working-directory: ./iac/infra-live
        env:
          TF_WORKSPACE: development
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Plan
        if: steps.infra-changed.outputs.any_changed == 'true'
        id: plan
        run: terraform plan -no-color
        working-directory: ./iac/infra-live
        env:
          TF_WORKSPACE: development
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        continue-on-error: false

  apply:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: apply infra
    needs:
      - validate_and_plan
    steps:
      - name: Terraform Apply
        if: steps.infra-changed.outputs.any_changed == 'true'
        id: apply
        run: terraform apply -auto-approve -input=false -no-color
        working-directory: ./iac/infra-live
        env:
          TF_WORKSPACE: development
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        continue-on-error: false
