name: Apply Infra

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./iac/base

jobs:
  validate_and_plan:
    runs-on: ubuntu-latest
    name: Apply Base Infra Changes
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: infra-live folder changed
        id: infra-changed
        uses: tj-actions/changed-files@v41
        with:
          files: |
            iac/base/**

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.5

      - name: Terraform fmt
        if: steps.infra-changed.outputs.any_changed == 'true'
        id: fmt
        run: terraform fmt -check
        continue-on-error: false

      - name: Terraform Init
        if: steps.infra-changed.outputs.any_changed == 'true'
        id: init
        run: terraform init
        env:
          TF_WORKSPACE: development

      - name: Terraform Validate
        if: steps.infra-changed.outputs.any_changed == 'true'
        id: validate
        run: terraform validate -no-color
        env:
          TF_WORKSPACE: development

      - name: Terraform Plan
        if: steps.infra-changed.outputs.any_changed == 'true'
        id: plan
        run: terraform plan -no-color
        env:
          TF_WORKSPACE: development
        continue-on-error: false

      - name: Terraform Apply
        if: steps.infra-changed.outputs.any_changed == 'true'
        id: apply
        run: terraform apply -auto-approve -input=false -no-color
        env:
          TF_WORKSPACE: development
        continue-on-error: false
