name: Build Application

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    name: rebuild changed apps
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: api folder changed
        id: api-changed
        uses: tj-actions/changed-files@v34
        with:
          files: |
            app/api/**

      - name: api test
        if: steps.api-changed.outputs.any_changed == 'true'
        working-directory: ./app/api
        run: |
          npm install
          npm test

      - name: api build
        if: steps.api-changed.outputs.any_changed == 'true'
        working-directory: ./app
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: api
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f Dockerfile.api -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          aws ssm put-parameter --name "/application/api/development/docker_tag" --type "SecureString" --value ${{ github.sha }} --overwrite

      - name: web folder changed
        id: web-changed
        uses: tj-actions/changed-files@v34
        with:
          files: |
            app/web/**

      - name: web test
        if: steps.web-changed.outputs.any_changed == 'true'
        working-directory: ./app/web
        run: |
          npm install
          npm test

      - name: web build
        if: steps.web-changed.outputs.any_changed == 'true'
        working-directory: ./app
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: web
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f Dockerfile.web -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          aws ssm put-parameter --name "/application/web/development/docker_tag" --type "SecureString" --value ${{ github.sha }} --overwrite
