name: Build Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: rebuild changed apps
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"

      - name: api folder changed
        id: api-changed
        uses: tj-actions/changed-files@v34
        with:
          files: |
            app/api/**

      - name: api build
        if: steps.api-changed.outputs.any_changed == 'true'
        working-directory: ./app
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: api
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f Dockerfile.api -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: web folder changed
        id: web-changed
        uses: tj-actions/changed-files@v34
        with:
          files: |
            app/web/**

      - name: web build
        if: steps.web-changed.outputs.any_changed == 'true'
        working-directory: ./app
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: web
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f Dockerfile.web -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
