name: Update Infra

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Build Application"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: app folder changed
        id: app-changed
        uses: tj-actions/changed-files@v34
        with:
          files: |
            app/**

      - name: update infra
        if: steps.app-changed.outputs.any_changed == 'true'
        run: |
          echo "Updating infra"
